# Generated by Django 5.0.2 on 2024-02-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_object_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slide_iamge',
            new_name='slide_image',
        ),
    ]
