# Generated by Django 5.0.2 on 2024-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_object_app', '0004_division_district_upazila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazila',
            name='upazila_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
