# Generated by Django 5.0.2 on 2024-02-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user_app', '0001_initial'),
        ('server_object_app', '0004_division_district_upazila'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_object_app.district'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_object_app.division'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_object_app.upazila'),
        ),
    ]
