# Generated by Django 5.0.2 on 2024-02-27 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_server_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_point',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('INCOMPLETED', 'Incompleted'), ('COMPLETED', 'Completed'), ('CANCEL', 'Cancel'), ('SHIPPING', 'Shipping'), ('PENDING', 'Pending'), ('HOLD', 'Hold'), ('PROCESSING', 'Processing')], max_length=100),
        ),
    ]
