# Generated by Django 5.0.2 on 2024-02-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_server_app', '0003_remove_order_user_order_address_order_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
