# Generated by Django 5.0.2 on 2024-02-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_server_app', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('INCOMPLETED', 'Incompleted'), ('COMPLETED', 'Completed'), ('CANCEL', 'Cancel'), ('SHIPPING', 'Shipping'), ('PENDING', 'Pending'), ('HOLD', 'Hold'), ('PROCESSING', 'Processing')], default='PENDING', max_length=100),
        ),
    ]
