# Generated by Django 5.0.2 on 2024-03-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_server_app', '0003_productsize_psize_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='psize_status',
            field=models.BooleanField(default=False),
        ),
    ]
