# Generated by Django 5.0.2 on 2024-03-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_server_app', '0004_alter_productsize_psize_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_third_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_server_app.rootcategorythree'),
        ),
    ]
